version: "3"

services:
  kutt:
    build: .
    container_name: kutt
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - kutt-network
      - nginx-proxy

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - kutt-network

  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: {$DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - kutt-network

networks:
  kutt-network:
    driver: "bridge"
  nginx-proxy:
    external:
      name: nginx-proxy
